<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>VacIntegrity</AssemblyName>
    <RootNamespace>VacIntegrityPlugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Carbon.dll">
      <HintPath>refs/Carbon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Carbon.Common.dll">
      <HintPath>refs/Carbon.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Carbon.SDK.dll">
      <HintPath>refs/Carbon.SDK.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Carbon.Test.dll">
      <HintPath>refs/Carbon.Test.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp.dll">
      <HintPath>refs/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
