<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>VacIntegrity</AssemblyName>
    <RootNamespace>VacIntegrityPlugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Carbon.dll">
      <HintPath>refs/Carbon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Carbon.SDK.dll">
      <HintPath>refs/Carbon.SDK.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Facepunch.UnityEngine.dll">
      <HintPath>refs/Facepunch.UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Facepunch.Console.dll">
      <HintPath>refs/Facepunch.Console.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp.dll">
      <HintPath>refs/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.dll">
      <HintPath>refs/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule.dll">
      <HintPath>refs/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
