[package]
name = "vac-client-linux"
version = "0.1.0"
edition = "2021"

[lib]
name = "vac_client_linux"
crate-type = ["cdylib", "lib"]

[dependencies]
vac-core = { path = "../vac-core" }
vac-sys = { path = "../vac-sys" }
vac-crypto = { path = "../vac-crypto" }
vac-client-core = { path = "../vac-client-core" }
