; VAC Anti-Cheat Windows Client Installer
; Requires Inno Setup 6+ (https://jrsoftware.org/isinfo.php)
; Build: iscc vac-setup.iss

#define MyAppName "VAC Anti-Cheat Client"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "VAC Team"
#define MyAppURL "https://github.com/text70/VAC"

[Setup]
AppId={{B6F3A2C1-7D4E-4F2A-9B1E-8C5D3A6F2E1D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
DefaultDirName={pf64}\Vac
DefaultGroupName=VAC
DisableProgramGroupPage=yes
OutputDir=Output
OutputBaseFilename=vac-setup
Compression=lzma2/max
SolidCompression=yes
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64
UninstallDisplayIcon={app}\vac-daemon-win.exe
SetupIconFile=

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "startdaemon"; Description: "Start VAC daemon after installation"; GroupDescription: "Startup"; Flags: checkedonce

[Files]
Source: "Source\vac.sys"; DestDir: "{app}"; Flags: ignoreversion
Source: "Source\vac-daemon-win.exe"; DestDir: "{app}"; Flags: ignoreversion

[Code]

var
  ServerPage: TInputQueryWizardPage;
  ServerIP: string;

procedure InitializeWizard;
begin
  ServerPage := CreateInputQueryPage(
    wpSelectDir,
    'Server Configuration',
    'Enter the VAC-enabled game server address',
    'The daemon will connect to this server to run anti-cheat scans. ' +
    'Enter the IP:port of your server (e.g., 192.168.1.100:28084)');
  ServerPage.Add('Server address:', False);
  ServerPage.Values[0] := '127.0.0.1:28084';
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = ServerPage.ID then
  begin
    ServerIP := Trim(ServerPage.Values[0]);
    if ServerIP = '' then
    begin
      MsgBox('Please enter a server address.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

function PrepareConfig(Server: string): string;
begin
  Result := '# VAC daemon config' + #13#10 +
            '# Auto-generated by installer' + #13#10 +
            'server=' + Server + #13#10;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigPath: string;
begin
  if CurStep = ssPostInstall then
  begin
    ConfigPath := ExpandConstant('{app}\vac-daemon.ini');
    SaveStringToFile(ConfigPath, PrepareConfig(ServerIP), False);
  end;
end;

procedure InstallDriver;
var
  ResultCode: Integer;
begin
  Log('Installing VAC kernel driver...');
  if not Exec('sc.exe', 'create Vac type= kernel binPath= "' + ExpandConstant('{app}') + '\vac.sys" start= auto',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    Log('sc create failed with code ' + IntToStr(ResultCode));
  end;
  Exec('sc.exe', 'start Vac', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure InstallDaemon;
var
  ResultCode: Integer;
begin
  Log('Installing VAC daemon service...');
  Exec('sc.exe', 'create VacDaemon binPath= "' + ExpandConstant('{app}') + '\vac-daemon-win.exe" start= auto displayname= "VAC Daemon"',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure RunSetupAfterInstall;
begin
  if IsTaskSelected('startdaemon') then
  begin
    InstallDriver;
    InstallDaemon;
    Exec('sc.exe', 'start VacDaemon', '', SW_HIDE, ewWaitUntilTerminated);
  end;
end;

[Run]
; After file copying, run the service installation and start
Filename: "{app}\vac-daemon-win.exe"; Description: "Run VAC daemon now"; Flags: postinstall nowait skipifsilent shellexec

[UninstallRun]
Filename: "sc.exe"; Parameters: "stop VacDaemon"; Flags: runhidden
Filename: "sc.exe"; Parameters: "delete VacDaemon"; Flags: runhidden
Filename: "sc.exe"; Parameters: "stop Vac"; Flags: runhidden
Filename: "sc.exe"; Parameters: "delete Vac"; Flags: runhidden